### ISSUE TITLE
ERROR: module_name must be supplied along with module_version.

### ISSUE THREAD

**Issue by MichaelStankiewicz** [smurawski/dsc_contrib#3]
I have a dsc_resource definition defined as such:

dsc_resource '[MyDscResource]Initialize_Server' do
  resource :MyDscResource
  module_version ps_module_spec('cMyModule', '2.3.1')
  property :foo, 'bar'
end

Based on the readme file for the dsc_contrib cookbook, this should work.  However I'm getting the error that I must specify 'module_name' as well.  But why would I need to do this?  The module name is already specified in the module_version construct.  Adding another line just to specify the same information already specified in the module_version construct seems redundant.

Am I missing something here?

**Comment by MichaelStankiewicz** [comment]
I'm going to close this issue.  I changed the construct from module_version to module_name, and the construct worked.  At a minimum, the README file for this cookbook should be updated to reflect module_name instead of module_version.

**Comment by usepowershell** [comment]
@MichaelStankiewicz Thanks.  Updated the readme.
